#!/usr/bin/env python3

import sys

MAX_TITLE_LENGTH = 50

commit_message_filename = sys.argv[1]

with open(sys.argv[1]) as commit_message_file:
    commit_title = commit_message_file.readline().strip()


if len(commit_title) > MAX_TITLE_LENGTH:
    print(f"Commit message too long: should be {MAX_TITLE_LENGTH} characters or less")
    sys.exit(1)

sys.exit(0)
