brew "bat"
brew "chezmoi"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnu-sed"
brew "just"
brew "kubernetes-cli"
brew "kustomize"
brew "lsd"
brew "ripgrep"
brew "snowflake-cli"
brew "starship"
brew "tree"
brew "wget"

if OS.mac?
  cask "1password-cli"
  cask "discord"
  cask "firefox"
  cask "font-hack-nerd-font"
  cask "google-drive"
  cask "iterm2"
  cask "keepassxc"
  cask "keepingyouawake"
  cask "ngrok"
  cask "obsidian"
  cask "raycast"
  cask "rectangle"
  cask "slack"
  cask "spotify"
  cask "visual-studio-code"
end

uv "asciinema"
uv "llm", with: ["llm-anthropic", "llm-fragments-pypi"]
uv "marimo"
uv "pgcli"
uv "prek"
uv "python-lsp-server[all]"
uv "rich-cli"
uv "ruff"
uv "ty"
uv "xonsh[full]", with: ["xontrib-vox"]
uv "yq"
