#!/usr/bin/env python3

import sys

MAX_TITLE_LENGTH = 50

commit_message_filename = sys.argv[1]

with open(commit_message_filename) as commit_message_file:
    commit_title = commit_message_file.readline().strip()


title_length = len(commit_title)
if title_length > MAX_TITLE_LENGTH:
    sys.stderr.write(f"Commit message too long: {title_length}/{MAX_TITLE_LENGTH} characters")
    sys.exit(1)

sys.exit(0)
