[directory]
truncation_length = 0
truncate_to_repo = false

[gcloud]
disabled = true

[kubernetes]
disabled = false
detect_env_vars = [
    "STARSHIP_ENABLE_MODULE_KUBERNETES",
]
# Workaround for https://github.com/starship/starship/issues/5978
# Only having the env var check doesn't work.
detect_files = [
    'THIS_FILE_WILL_NEVER_EXIST'
]
contexts = [
    { context_pattern = "[^-]+-devops.*", context_alias = "devops", style = "blue" },
    { context_pattern = "[^-]+-staging.*", context_alias = "staging", style = "yellow" },
    { context_pattern = "[^-]+-prod.*", context_alias = "prod", style = "red" },
]

[package]
disabled = true
