[directory]
truncation_length = 0
truncate_to_repo = false

[docker_context]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = false
detect_env_vars = [
    "STARSHIP_ENABLE_MODULE_KUBERNETES",
]
contexts = [
    { context_pattern = ".*-devops.*", context_alias = "devops", style = "blue bold" },
    { context_pattern = ".*-staging.*", context_alias = "staging", style = "yellow bold" },
    { context_pattern = ".*-prod.*", context_alias = "prod", style = "red bold" },
]

[package]
disabled = true

[python]
python_binary = [
    ["uv", "run", "--no-python-downloads", "python"]
]
